2025-06-14 02:28:50,005 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 02:30:11,412 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 02:31:55,106 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.

2025-06-14 02:35:29,370 - WARNING - Not Found: /favicon.ico
2025-06-14 02:35:43,697 - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-06-14 02:36:38,810 - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-06-14 02:39:20,240 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 02:39:49,843 - INFO - D:\PRUEBAS\drf-scrapping\scrap\main.py changed, reloading.
2025-06-14 02:40:24,414 - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-06-14 02:40:41,878 - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-06-14 02:40:51,832 - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-06-14 02:40:58,980 - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-06-14 12:56:25,969 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 12:56:34,993 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 12:56:40,637 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 12:56:50,501 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:02:14,843 - ERROR - Internal Server Error: /api/novels/6/chapters/1693/
Traceback (most recent call last):
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: get_or_create_chapter() got an unexpected keyword argument 'novel_id'
2025-06-14 13:02:14,886 - ERROR - Internal Server Error: /api/novels/6/chapters/1693/
Traceback (most recent call last):
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: get_or_create_chapter() got an unexpected keyword argument 'novel_id'
2025-06-14 13:02:38,447 - ERROR - Internal Server Error: /api/novels/1/chapters/1/
Traceback (most recent call last):
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: get_or_create_chapter() got an unexpected keyword argument 'novel_id'
2025-06-14 13:02:38,485 - ERROR - Internal Server Error: /api/novels/1/chapters/1/
Traceback (most recent call last):
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: get_or_create_chapter() got an unexpected keyword argument 'novel_id'
2025-06-14 13:03:17,719 - ERROR - Internal Server Error: /api/novels/1/chapters/1/
Traceback (most recent call last):
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: get_or_create_chapter() got an unexpected keyword argument 'novel_id'
2025-06-14 13:03:17,771 - ERROR - Internal Server Error: /api/novels/1/chapters/1/
Traceback (most recent call last):
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PRUEBAS\drf-scrapping\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: get_or_create_chapter() got an unexpected keyword argument 'novel_id'
2025-06-14 13:04:32,683 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:06:38,379 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:07:21,555 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:08:28,018 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:09:10,959 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:22:01,820 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:22:13,578 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:22:20,172 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:22:28,183 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:22:42,432 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:22:48,195 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:24:10,701 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:24:16,270 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:24:31,174 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:24:42,966 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:24:48,301 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:24:52,701 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:32:23,160 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:33:09,801 - INFO - D:\PRUEBAS\drf-scrapping\api\urls.py changed, reloading.
2025-06-14 13:36:12,197 - INFO - D:\PRUEBAS\drf-scrapping\scrap\main.py changed, reloading.
2025-06-14 13:36:54,014 - INFO - D:\PRUEBAS\drf-scrapping\scrap\main.py changed, reloading.
2025-06-14 13:40:46,120 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:40:47,288 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:42:29,590 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:42:30,798 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:46:07,249 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:49:26,819 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:49:51,146 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:50:08,803 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:50:50,773 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:50:51,984 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:51:42,729 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:51:43,893 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:54:20,841 - INFO - D:\PRUEBAS\drf-scrapping\scrap\main.py changed, reloading.
2025-06-14 13:54:29,414 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:54:30,621 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:54:56,612 - INFO - D:\PRUEBAS\drf-scrapping\scrap\main.py changed, reloading.
2025-06-14 13:55:03,344 - INFO - D:\PRUEBAS\drf-scrapping\scrap\main.py changed, reloading.
2025-06-14 13:55:11,184 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:55:12,392 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 13:57:21,525 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:57:51,128 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:57:56,875 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:58:29,720 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 13:58:36,338 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 14:05:19,849 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 14:05:21,015 - ERROR - Internal Server Error: /api/novels/4/chapters/764/audio/
2025-06-14 14:06:30,310 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 14:07:12,240 - INFO - D:\PRUEBAS\drf-scrapping\api\views.py changed, reloading.
2025-06-14 14:07:22,257 - INFO - 🚀 Iniciando procesamiento de novela en: https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1
2025-06-14 14:07:22,257 - INFO - Configurando Chrome con traducción (Intento 1/3)...
2025-06-14 14:07:23,566 - INFO - ✅ Chrome con traducción configurado exitosamente
2025-06-14 14:07:23,581 - INFO - 📚 Driver creado con éxito: https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1
2025-06-14 14:07:27,965 - ERROR - ❌ Error procesando novela https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1: duplicate key value violates unique constraint "api_novel_novel_url_key"
DETAIL:  Key (novel_url)=() already exists.

2025-06-14 14:07:33,219 - INFO - 🚀 Iniciando procesamiento de novela en: https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1
2025-06-14 14:07:33,219 - INFO - Configurando Chrome con traducción (Intento 1/3)...
2025-06-14 14:07:34,533 - INFO - ✅ Chrome con traducción configurado exitosamente
2025-06-14 14:07:34,533 - INFO - 📚 Driver creado con éxito: https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1
2025-06-14 14:07:38,552 - ERROR - ❌ Error procesando novela https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1: duplicate key value violates unique constraint "api_novel_novel_url_key"
DETAIL:  Key (novel_url)=() already exists.

2025-06-14 14:07:53,087 - INFO - 🚀 Iniciando procesamiento de novela en: https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1
2025-06-14 14:07:53,087 - INFO - Configurando Chrome con traducción (Intento 1/3)...
2025-06-14 14:07:54,330 - INFO - ✅ Chrome con traducción configurado exitosamente
2025-06-14 14:07:54,330 - INFO - 📚 Driver creado con éxito: https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1
2025-06-14 14:07:58,375 - ERROR - ❌ Error procesando novela https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1: duplicate key value violates unique constraint "api_novel_novel_url_key"
DETAIL:  Key (novel_url)=() already exists.

2025-06-14 14:08:03,777 - INFO - 🚀 Iniciando procesamiento de novela en: https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1
2025-06-14 14:08:03,777 - INFO - Configurando Chrome con traducción (Intento 1/3)...
2025-06-14 14:08:05,095 - INFO - ✅ Chrome con traducción configurado exitosamente
2025-06-14 14:08:05,095 - INFO - 📚 Driver creado con éxito: https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1
2025-06-14 14:08:09,157 - ERROR - ❌ Error procesando novela https://www.royalroad.com/fiction/28578/unfathomable-senior/chapter/427894/chapter-1: duplicate key value violates unique constraint "api_novel_novel_url_key"
DETAIL:  Key (novel_url)=() already exists.

